### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by sherkwast** [fhueske/flink-sql-demo#2]
When running `docker-compose build` in the flink-sql-demo directory, it gave errors like following, 

> --2020-04-27 01:55:28--  http://apache.lauf-forum.at/hive/hive-2.3.6/apache-hive-2.3.6-bin.tar.gz
Resolving apache.lauf-forum.at (apache.lauf-forum.at)... 136.243.81.188, 2a01:4f8:212:2f98::101
Connecting to apache.lauf-forum.at (apache.lauf-forum.at)|136.243.81.188|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://apache.lauf-forum.at/hive/hive-2.3.6/apache-hive-2.3.6-bin.tar.gz [following]
--2020-04-27 01:55:29--  https://apache.lauf-forum.at/hive/hive-2.3.6/apache-hive-2.3.6-bin.tar.gz
Connecting to apache.lauf-forum.at (apache.lauf-forum.at)|136.243.81.188|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-27 01:55:30 ERROR 404: Not Found.

And I tried to connect to http://apache.lauf-forum.at/hive/hive-2.3.6/apache-hive-2.3.6-bin.tar.gz in the browser, it also gave '404 Not Found' error.

**Comment by fhueske** [comment]
Thanks for reporting the problem @sherkwast.
I fixed the download link.
Please let me know if there are further issues.

Thanks, Fabian
